[package]
name = "pathman"
version = "0.1.0"
authors = ["Andrew Chin <achin@eminence32.net>"]

[dependencies]
setenv = "*"
clap = "*"
term = "*"
rustyline = { version = "9.1.2" }

[target.'cfg(windows)'.dependencies]
winapi = "*"
