[package]
name = "pathman"
version = "0.1.0"
authors = ["Andrew Chin <achin@eminence32.net>"]

[dependencies]
setenv = "*"
clap = "4.5.43"
term = "1.1.0"
rustyline = { version = "17.0.0" }

[target.'cfg(windows)'.dependencies]
winapi = "*"
